import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const pos_tickets_tables: KirletTableDecl[] = [
  {
    name: "pos_tickets",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "ticket_sequence", type: "text" },
      { name: "ticket_type", type: "text" },
      { name: "pos_session", type: "text" },
      { name: "subtotal", type: "real" },
      { name: "total_paid", type: "real" },
      { name: "change", type: "real" },
      { name: "client_id", type: "text" },
      { name: "client_name", type: "text" },
      { name: "client_lastname", type: "text" },
      { name: "client_home", type: "text" },
      { name: "items", type: "text" },
      { name: "item_id", type: "text" },
      { name: "quantity", type: "real" },
      { name: "total", type: "real" },
      { name: "unit_price", type: "real" },
      { name: "price_origin", type: "text" },
      { name: "withdrawal_amount", type: "real" },
      { name: "withdrawal_reason", type: "text" },
      { name: "withdrawal_signature", type: "text" },
    ],
    indexes: [
      { name: "idx_pos_tickets_name", columns: ["name"] },
      { name: "idx_pos_tickets_active", columns: ["is_active"] },
    ],
  },
];
