import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { pos_session_pages } from "./pos-session.pages.ts";
import { pos_session_tables } from "./pos-session.tables.ts";

export const pos_session_module = define_module({
  resource: "pos-session",
  labels: {
    singular: "Sesiones POS",
    plural: "Sesiones POS",
    read: "Ver Sesiones POS",
    write: "Editar Sesiones POS",
  },
  routes: define_crud({
    resource: "pos-session",
    table: "pos_session",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "pos-sess",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      reference: { type: "string", search: true },
      partner_id: { type: "string", search: true },
      partner_name: { type: "string", search: true },
      partner_lastname: { type: "string", search: true },
      partner_home: { type: "string", search: true },
      date_order: { type: "string", search: true },
      amount_total: { type: "number" },
      lines: { type: "string", search: true },
      sync: { type: "boolean" },
      product_id: { type: "string", search: true },
      product: { type: "string", search: true },
      price_unit: { type: "number" },
      quantity: { type: "number" },
      sale_order_id: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: pos_session_tables,
  pages: pos_session_pages,
  menu: [
    {
      id: "pos.pos-session",
      label: "Sesiones POS",
      order: 0,
      pageId: "pos.pos-session",
      path: "pos-session",
      permission: "subject.pos.pos-session.read",
      icon: "document",
    },
    {
      id: "pos.pos",
      label: "Estación POS",
      order: 0,
      pageId: "pos.pos",
      path: "pos",
      permission: "subject.pos.pos.read",
      icon: "document",
    },
    {
      id: "pos.pos-tickets",
      label: "Tickets",
      order: 0,
      pageId: "pos.pos-tickets",
      path: "pos-tickets",
      permission: "subject.pos.pos-tickets.read",
      icon: "document",
    },
    {
      id: "pos.pos-order",
      label: "Ordenes",
      order: 1,
      pageId: "pos.pos-order",
      path: "pos-order",
      permission: "subject.pos.pos-order.read",
      icon: "document",
    }
    ],
});
